font:
  header: Unifont 12 bold
  card: Unifont 12
  counter: Unifont 12
  timer: Unifont 18
width: 800
height: 480
margin: 10
headersize: 25
dashed: False
daycounter: 0
theme: prime
customtheme:
  bg: black
  main: blueviolet
  secondary: grey50
  emptyslot: grey10
  sectionhighlight: '#060015'
  buttonhighlight: grey10
  pal0: white
  pal1: lime
  pal2: cyan
  pal3: dodgerblue
  pal4: magenta
  pal5: yellow
  pal6: orangered
sections:
  - name: TO DO
    width: 200
    cards: 4
  - name: IN PROGRESS
    width: 400
    cards: 2
  - name: FINISHED
    width: 200
    cards: 5
