width: 800
height: 480
headersize: 20
margin: 7
dashed: false
daycounter: 0
sections:
- name: TODO
  width: 225
  cards: 9
- name: IN PROGRESS
  width: 575
  cards: 3
font:
  card: Unifont 12
  counter: Unifont 10
  header: Unifont 14 bold
  timer: Unifont 18
customtheme:
  bg: black
  main: blueviolet
  secondary: grey50
  emptyslot: grey10
  buttonhighlight: grey10
  sectionhighlight: '#060015'
  palette0: white
  palette1: lime
  palette2: cyan
  palette3: dodgerblue
  palette4: magenta
  palette5: yellow
  palette6: orangered
theme: prime
