name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
            pip install pyinstaller pyyaml pillow

      - name: Set icon based on OS
        shell: bash  # Ensures Bash is used, even on Windows
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "ICON=icon.icns" >> $GITHUB_ENV
          else
            echo "ICON=icon.ico" >> $GITHUB_ENV
          fi

      - name: Build binary using PyInstaller
        run: |
          pyinstaller --onefile  --noconsole --icon=$ICON kanbuddy.py
          mv dist/* .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: |
            kanbuddy.exe
            kanbuddy
            settings.yaml
            readme.md
