name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: Install dependencies
        run: |
            pip install pyinstaller pyyaml pillow

      - name: Build binary using PyInstaller
        run: |
          pyinstaller --onefile  --noconsole --icon=icon.ico kanbuddy.py
          mv dist/* .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kanbuddy-${{ matrix.os }}
          path: |
            kanbuddy.exe
            icon.ico
            kanbuddy
            settings.yaml
            readme.md
